version: '3'

services:
  web:
    image: nginx
    volumes:
      - "./:/var/www/app:ro"
      - "./docker/web/vhost.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - db
      - cache

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GUID: ${GUID:-1000}
        TZ: ${TZ:-UTC}
    volumes:
      - "./:/var/www/app"
      - "./docker/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    depends_on:
      - db
      - cache

  db:
    image: postgres
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-laravel}

  cache:
    image: redis
    volumes:
      - "cache_data:/data"

volumes:
  db_data:
    driver: local

  cache_data:
    driver: local
